# Generated by Django 3.2.5 on 2022-03-29 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_alter_flight_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['arrivalname']},
        ),
    ]
