# Generated by Django 3.2.5 on 2022-04-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0027_alter_flight_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='pd_photo',
            field=models.TextField(max_length=100, null=True, verbose_name='商品照片'),
        ),
    ]
