# Generated by Django 3.2.5 on 2023-08-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0028_flight_pd_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='first_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_loop_001', models.CharField(max_length=30)),
                ('pic_loop_002', models.CharField(max_length=30)),
                ('pic_loop_003', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='flight',
            name='items',
            field=models.CharField(choices=[('衣服', '衣服'), ('褲子', '褲子'), ('鞋子', '鞋子'), ('配件', '配件'), ('保養品', '保養品'), ('化妝品', '化妝品'), ('保健食品', '保健食品'), ('精品名牌', '精品名牌')], max_length=20),
        ),
    ]
