# Generated by Django 3.2.5 on 2023-08-15 07:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0029_auto_20230805_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='first_page',
            name='text_block_001',
            field=ckeditor.fields.RichTextField(blank=True, default='輸入', max_length=10000, null=True, verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='first_page',
            name='pic_loop_001',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='first_page',
            name='pic_loop_002',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='first_page',
            name='pic_loop_003',
            field=models.CharField(max_length=999),
        ),
    ]
